# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html

# Logo Image Source
logo_src: /images/logo.svg

# Theme Main Subtitle
subtitle_main: Ying Xu's Portfolio

# Theme Secondary subtitle
susbtitle_secondary: My introduction.

# Footer About Section
about_footer: Linkedin <a href="https://www.linkedin.com/in/ying-yuki-xu/" target="_blank">https://www.linkedin.com/in/ying-yuki-xu/</a> <br /> Github <a href="https://github.com/gracexu414/" target="_blank">https://github.com/gracexu414/</a> <br /> Email xu.ying1#northeastern.edu <br />

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: klugjo
  # Facebook comments
#  facebook:
#    appid:
#    comment_count: 5
#    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
#twitter_url: https://twitter.com/?lang=en
#facebook_url: https://www.facebook.com/
#instagram_url: https://www.instagram.com/
#dribble_url: https://dribbble.com/
github_url: https://github.com/gracexu414/
linkedin_url: https://www.linkedin.com/in/ying-yuki-xu/
#dribble_url: https://www.linkedin.com/in/ying-yuki-xu/
#googleplus_url: https://plus.google.com/
#behance_url: https://www.behance.net/
#fivehundredpx_url: https://500px.com/
email_url: mailto:xu.ying1@northeastern.edu
phone_number: tel:4146660722
#rss_url: \#
